<?php
require 'vendor/autoload.php';
$client = new MongoDB\Client;

// Create and use database
// $client->databasename;
$companydb = $client->companydb;

// Create collection
// $create_collection = $companydb->createCollection('empcollection');

// Use collection
// $companydb->collectionname
$empcollection = $companydb->empcollection;

/* =======================
    INSERT MANY DOCUMENTS
========================== */
/* $insertManyResult = $empcollection->insertMany([
    [
        '_id' => 2, // if not define mongodb create autogenerated id
        'name' => 'Kyle',
        'age' => 11,
        'skill' => 'MongoDB'
    ],
    [
        '_id' => 3, // if not define mongodb create autogenerated id
        'name' => 'Ryle',
        'age' => 1,
        'skill' => 'MongoDB'
    ],
    [
        '_id' => 4, // if not define mongodb create autogenerated id
        'name' => 'Nikki',
        'age' => 32,
        'skill' => 'AngularJS'
    ]
]);
printf( "Inserted %d documents", $insertManyResult->getInsertedCount() );
var_dump( $insertManyResult->getInsertedIds() ); */


/* =======================
    INSERT SINGLE DOCUMENT
========================== */
/* $insertOneResult = $empcollection->insertOne(
    [
        '_id' => 1, // if not define mongodb create autogenerated id
        'name' => 'Ron',
        'age' => 28,
        'skill' => 'php'
    ]
);
printf( "Inserted %d documents", $insertOneResult->getInsertedCount() );
var_dump( $insertOneResult->getInsertedId() ); */


?>